### ISSUE TITLE
Protect privacy by masking timestamps

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-rum-collector#192]
At the moment, we log timestamps as-is. Through matching RUM timestamps to timestamps received from other sources (however unlikely) such as ISP logs (e.g. upon law enforcement request), there is a slim chance that timestamps could be associated with a particular visitor.

To reduce this chance, we use the new `t` property introduced in https://github.com/adobe/helix-rum-js/pull/84 to further reduce the entropy contained in our logs.

1. take the `Date.now()`
2. round it to current hour
3. add `t`
4. use the result as the `time` for all logs

**Comment by bosschaert** [comment]
I will see if I can implement this (can't assign the issue at the moment).
