### ISSUE TITLE
Protect privacy by masking user agents

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-rum-collector#193]
Instead of logging full user agents, we log only the device class:
- `mobile`: if user agent includes the word `mobile`
- `bot`: if it includes "bot", "crawler" or "spider"
- `desktop` otherwise

**Comment by bosschaert** [comment]
I came across these 2 user agents:
* **AHC/2.1** - I assume this is 'bot' too?
* **Opera/9.80 (SpreadTrum; Opera Mini/4.4.33961/191.315; U; fr) Presto/2.12.423 Version/12.16** - I guess this is 'mobile' as well
WDYT?
