### ISSUE TITLE
Guard against invalid JSON

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-rum-collector#2]
Invalid JSON bodies just fail badly with an error 500:

`stderr | 1cc70987 | abort: Unexpected input end in ~lib/assemblyscript-json/decoder.ts(156:5)`﻿

I'm not sure how to catch parse errors with `assemblyscript-json` yet.

**Comment by trieloff** [comment]
See https://github.com/nearprotocol/assemblyscript-json/issues/225

**Comment by davidnuescheler** [comment]
hmm... also, are there some that are sent by browsers, or is this just from testing?
considering this...

https://github.com/adobe/theblog/blob/master/scripts/martech.js#L164

i would be really surprised if actual browsers send something broken here.

**Comment by trieloff** [comment]
Me too, and so far the only occurrence is this one:

```
stdout | 41c8d0b1 | request received{"time":1622134614271,"host":"rum.hlx3.page","url":"https://rum.hlx3.page/.rum/1","user_agent":"lars is messing around","CLS":1.0,"LCP":1.0}
stderr | 1cc70987 | abort: Unexpected input end in ~lib/assemblyscript-json/decoder.ts(156:5)
```

The user agent tells the story.
