### ISSUE TITLE
Why "Both spellings are allowed." for referrer ?

### ISSUE THREAD

**Issue by ieb** [adobe/helix-rum-collector#212]
## Overview

The http spec has only one spelling. It might be a typo, it it is the spec.

## Details

"The misspelling of [referrer](https://en.wiktionary.org/wiki/referrer) was introduced in the original proposal by computer scientist [Phillip Hallam-Baker](https://en.wikipedia.org/wiki/Phillip_Hallam-Baker) to incorporate the "Referer" header field into the [HTTP](https://en.wikipedia.org/wiki/HTTP) specification.[[7]](https://en.wikipedia.org/wiki/HTTP_referer#cite_note-hallam-baker-7) The misspelling was set in stone by the time (May 1996) of its incorporation into the [Request for Comments](https://en.wikipedia.org/wiki/Request_for_Comments) standards document RFC 1945[[8]](https://en.wikipedia.org/wiki/HTTP_referer#cite_note-rfc1945-8) (which 'reflects common usage of the protocol referred to as "HTTP/1.0"' at that time); document co-author [Roy Fielding](https://en.wikipedia.org/wiki/Roy_Fielding) remarked in March 1995 that "neither one (referer or referrer) is understood by" the standard [Unix spell checker](https://en.wikipedia.org/wiki/Spell_(Unix)) of the period.[[9]](https://en.wikipedia.org/wiki/HTTP_referer#cite_note-fielding-9) "Referer" has since become a widely used spelling in the industry when discussing HTTP referrers; usage of the misspelling is not universal, though, as the correct spelling "referrer" is used in some web specifications such as the Referrer-Policy HTTP header or the [Document Object Model](https://en.wikipedia.org/wiki/Document_Object_Model).[[3]](https://en.wikipedia.org/wiki/HTTP_referer#cite_note-Leak-3)"
From https://en.wikipedia.org/wiki/HTTP_referer

## Proposed Actions

Use only one spelling. If its the Referer header, then use referer.

**Comment by trieloff** [comment]
We are used both by HTTP-influenced clients and JS-influenced clients. JS does not have the misspelling https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer

**Comment by randolf** [comment]
> We are used both by HTTP-influenced clients and JS-influenced clients. JS does not have the misspelling https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer

If the JavaScript clients are sending the wrong HTTP header with the correct spelling of "referrer" rather than the standards-documented spelling of "REFERER" (which, unfortunateyl, is a misspelling from the 1990s), then the JavaScript clients are non-compliant with the HTTP specification and that will have to be fixed.  ("Was the JavaScript code even tested in the first place?" is one question that probably should also be asked.)
