### ISSUE TITLE
Deploy as Cloudflare Worker

### ISSUE THREAD

**Issue by bosschaert** [adobe/helix-rum-collector#229]
Currently the rum collector only support deployment to Fastly Compute@Edge. 
We should support Cloudflare Workers as a target too. Via `hedy` we should be able to deploy to either.

**Comment by bosschaert** [comment]
Progress... with this command I can manually deploy the rum collector to Cloudflare:
```
 npx hedy --build --verbose --deploy --target cloudflare --arch node --arch edge --cloudflare-email bosschae@adobe.com --cloudflare-account-id abc --update-package true --directory /.../temp --entryFile ~/clones/helix-rum-collector/src/index.mjs --cloudflare-auth yyy --name rum-collector --package.name bosschae --externals fastly:logger
```

**Comment by chicharr** [comment]
I have some, yes. 
Do we need any changes in the code other than the endpoint?

**Comment by bosschaert** [comment]
@chicharr I don't think there is any other changes needed. Just an endpoint change.

**Comment by bosschaert** [comment]
Closing this issue as done. @chicharr if more work is needed just open a new issue 😄
