### ISSUE TITLE
Support Cloudflare Logging

### ISSUE THREAD

**Issue by bosschaert** [adobe/helix-rum-collector#230]
We should support Cloudflare Logging as an alternative to the Fastly Logging.

The runtime should automatically select the correct logging subsystem based on the current runtime. 

Depends on #232

**Comment by bosschaert** [comment]
My understanding is that that for Cloudflare logging we should just write the log messages to `console.log()`.

@trieloff could you please confirm? Is there also a special format that the logs need to be output in?

**Comment by trieloff** [comment]
As long as we `console.log({})` an object, we should be able to ingest it.

**Comment by bosschaert** [comment]
> As long as we `console.log({})` an object, we should be able to ingest it.

Something like this? https://github.com/adobe/helix-rum-collector/pull/236
